server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: ServiceApplication
          uri: http://localhost:8082
          predicates:
            - Path=/serviceApplications/**, /formTemplates/**, /serviceApplicationStatuses/**, /serviceApplicationDrafts/**, /serviceApplicationFormMappings/**, /formTemplatePreviews/**
        - id: EligibilityVerification
          uri: http://localhost:8083
          predicates:
            - Path=/eligibilityChecks/**, /eligibilityInquiryHistories/**
        - id: DataCollection
          uri: http://localhost:8084
          predicates:
            - Path=/externalData/**, /externalDataQueryHistories/**
        - id: ApplicationDocument
          uri: http://localhost:8085
          predicates:
            - Path=/applicationDocuments/**, /applicationDocumentDetails/**
        - id: DocumentIssuance
          uri: http://localhost:8086
          predicates:
            - Path=/issuedDocuments/**, /issuedDocumentStatuses/**
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: ServiceApplication
          uri: http://serviceApplication:8080
          predicates:
            - Path=/serviceApplications/**, /formTemplates/**, 
        - id: EligibilityVerification
          uri: http://eligibilityVerification:8080
          predicates:
            - Path=/eligibilityChecks/**, 
        - id: DataCollection
          uri: http://dataCollection:8080
          predicates:
            - Path=/externalData/**, 
        - id: ApplicationDocument
          uri: http://applicationDocument:8080
          predicates:
            - Path=/applicationDocuments/**, 
        - id: DocumentIssuance
          uri: http://documentIssuance:8080
          predicates:
            - Path=/issuedDocuments/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
