---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ServiceApplication
  labels:
    app: ServiceApplication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ServiceApplication
  template:
    metadata:
      labels:
        app: ServiceApplication
    spec:
      containers:
        - name: ServiceApplication
          image: username/ServiceApplication:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: EligibilityVerification
  labels:
    app: EligibilityVerification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: EligibilityVerification
  template:
    metadata:
      labels:
        app: EligibilityVerification
    spec:
      containers:
        - name: EligibilityVerification
          image: username/EligibilityVerification:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: DataCollection
  labels:
    app: DataCollection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: DataCollection
  template:
    metadata:
      labels:
        app: DataCollection
    spec:
      containers:
        - name: DataCollection
          image: username/DataCollection:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ApplicationDocument
  labels:
    app: ApplicationDocument
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ApplicationDocument
  template:
    metadata:
      labels:
        app: ApplicationDocument
    spec:
      containers:
        - name: ApplicationDocument
          image: username/ApplicationDocument:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: DocumentIssuance
  labels:
    app: DocumentIssuance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: DocumentIssuance
  template:
    metadata:
      labels:
        app: DocumentIssuance
    spec:
      containers:
        - name: DocumentIssuance
          image: username/DocumentIssuance:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: ServiceApplication
  labels:
    app: ServiceApplication
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: ServiceApplication


---


apiVersion: v1
kind: Service
metadata:
  name: EligibilityVerification
  labels:
    app: EligibilityVerification
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: EligibilityVerification


---


apiVersion: v1
kind: Service
metadata:
  name: DataCollection
  labels:
    app: DataCollection
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: DataCollection


---


apiVersion: v1
kind: Service
metadata:
  name: ApplicationDocument
  labels:
    app: ApplicationDocument
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: ApplicationDocument


---


apiVersion: v1
kind: Service
metadata:
  name: DocumentIssuance
  labels:
    app: DocumentIssuance
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: DocumentIssuance

