apiVersion: apps/v1
kind: Deployment
metadata:
  name: EligibilityVerification
  labels:
    app: EligibilityVerification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: EligibilityVerification
  template:
    metadata:
      labels:
        app: EligibilityVerification
    spec:
      containers:
        - name: EligibilityVerification
          image: "username/EligibilityVerification:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
