apiVersion: v1
kind: Service
metadata:
  name: EligibilityVerification
  labels:
    app: EligibilityVerification
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: EligibilityVerification