apiVersion: apps/v1
kind: Deployment
metadata:
  name: DocumentIssuance
  labels:
    app: DocumentIssuance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: DocumentIssuance
  template:
    metadata:
      labels:
        app: DocumentIssuance
    spec:
      containers:
        - name: DocumentIssuance
          image: "username/DocumentIssuance:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
