apiVersion: apps/v1
kind: Deployment
metadata:
  name: ApplicationDocument
  labels:
    app: ApplicationDocument
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ApplicationDocument
  template:
    metadata:
      labels:
        app: ApplicationDocument
    spec:
      containers:
        - name: ApplicationDocument
          image: "username/ApplicationDocument:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
