apiVersion: v1
kind: Service
metadata:
  name: ApplicationDocument
  labels:
    app: ApplicationDocument
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: ApplicationDocument